# Generated by Django 5.0.3 on 2024-08-04 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remover', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='backgrounds/')),
            ],
        ),
        migrations.RemoveField(
            model_name='imageupload',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='remover.backgroundimage'),
        ),
    ]
